# base image
FROM node:15

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /app/package.json
RUN npm install
RUN npm install @vue/cli -g

# start app with
#docker run -v ${PWD}:/app -v /app/node_modules -p 80:8080 --rm invidivue:dev
# build app with
# docker build -t ivnidvue:dev .
CMD ["npm", "run", "serve"]