# base image
FROM node:15

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH
#Cookie secret
ENV COOKIE_SECRET=
ENV SERVER_PORT=5000
ENV SERVER_HOSTNAME=localhost
ENV SERVER_TOKEN_EXPIRETIME_ACCESS=
ENV SERVER_TOKEN_SECRET=
ENV SERVER_TOKEN_ISSUER=
ENV SERVER_ADMIN_NAME=
ENV SERVER_ADMIN_PASSWORD=
ENV SERVER_TOKEN_EXPIRETIME_REFRESH

# install and cache app dependencies
COPY package.json /app/package.json
RUN npm install


# start app with
# docker run -v ${PWD}:/app -v /app/node_modules --rm api:dev
# build app with
# docker build -t api:dev .
CMD ["npm", "run", "start"]